# AUTOGENERATED by scripts/parse_f16_dml.py from assets/F16_aero.dml — do not edit.
# Verification checkcases embedded in the DAVE-ML source (staticShot elements).
# Inputs: vt (ft/s), alpha/beta/el/ail/rdr (deg), p/q/r (rad/s), xcg (fraction of cbar).
# Outputs: nondimensional body-axis coefficients. tol is the DML per-signal tolerance.

const F16_AERO_CHECKCASES = [
    (name = "Nominal", inputs = (vt = 300, alpha = 5, beta = 0, p = 0, q = 0, r = 0, el = 0, ail = 0, rdr = 0, xcg = 0.25), expected = (cx = -0.004, cy = 0, cz = -0.416, cl = 0, cm = -0.0466, cn = 0), tol = 1e-06),
    (name = "Positive sideslip", inputs = (vt = 300, alpha = 5, beta = 2.34, p = 0, q = 0, r = 0, el = 0, ail = 0, rdr = 0, xcg = 0.25), expected = (cx = -0.004, cy = -0.0468, cz = -0.41530612733219, cl = -0.005616, cm = -0.04653061273322, cn = 0.01065792), tol = 1e-06),
    (name = "Negative sideslip", inputs = (vt = 300, alpha = 5, beta = -2.34, p = 0, q = 0, r = 0, el = 0, ail = 0, rdr = 0, xcg = 0.25), expected = (cx = -0.004, cy = 0.0468, cz = -0.41530612733219, cl = 0.005616, cm = -0.04653061273322, cn = -0.01065792), tol = 1e-06),
    (name = "Positive roll rate", inputs = (vt = 300, alpha = 5, beta = 0, p = 3.42, q = 0, r = 0, el = 0, ail = 0, rdr = 0, xcg = 0.25), expected = (cx = -0.004, cy = 0.01881, cz = -0.416, cl = -0.07182, cm = -0.0466, cn = -0.002761764), tol = 1e-06),
    (name = "Negative roll rate", inputs = (vt = 300, alpha = 5, beta = 0, p = -3.42, q = 0, r = 0, el = 0, ail = 0, rdr = 0, xcg = 0.25), expected = (cx = -0.004, cy = -0.01881, cz = -0.416, cl = 0.07182, cm = -0.0466, cn = 0.002761764), tol = 1e-06),
    (name = "Positive pitch rate", inputs = (vt = 300, alpha = 5, beta = 0, p = 0, q = 0.98, r = 0, el = 0, ail = 0, rdr = 0, xcg = 0.25), expected = (cx = 0.02077570666667, cy = 0, cz = -0.99656506666667, cl = 0, cm = -0.2019104, cn = 0), tol = 1e-06),
    (name = "Negative pitch rate", inputs = (vt = 300, alpha = 5, beta = 0, p = 0, q = -0.98, r = 0, el = 0, ail = 0, rdr = 0, xcg = 0.25), expected = (cx = -0.02877570666667, cy = 0, cz = 0.16456506666667, cl = 0, cm = 0.1087104, cn = 0), tol = 1e-06),
    (name = "Positive yaw rate", inputs = (vt = 300, alpha = 5, beta = 0, p = 0, q = 0, r = 2.92, el = 0, ail = 0, rdr = 0, xcg = 0.25), expected = (cx = -0.004, cy = 0.139868, cz = -0.416, cl = 0.016498, cm = -0.0466, cn = -0.06163368586667), tol = 1e-06),
    (name = "Negative yaw rate", inputs = (vt = 300, alpha = 5, beta = 0, p = 0, q = 0, r = -2.92, el = 0, ail = 0, rdr = 0, xcg = 0.25), expected = (cx = -0.004, cy = -0.139868, cz = -0.416, cl = -0.016498, cm = -0.0466, cn = 0.06163368586667), tol = 1e-06),
    (name = "Positive elevator", inputs = (vt = 300, alpha = 5, beta = 0, p = 0, q = 0, r = 0, el = 12.92, ail = 0, rdr = 0, xcg = 0.25), expected = (cx = -0.02860333333333, cy = 0, cz = -0.514192, cl = 0, cm = -0.1834792, cn = 0), tol = 1e-06),
    (name = "Negative elevator", inputs = (vt = 300, alpha = 5, beta = 0, p = 0, q = 0, r = 0, el = -12.92, ail = 0, rdr = 0, xcg = 0.25), expected = (cx = -0.02422, cy = 0, cz = -0.317808, cl = 0, cm = 0.08481253333333, cn = 0), tol = 1e-06),
    (name = "Positive aileron", inputs = (vt = 300, alpha = 5, beta = 0, p = 0, q = 0, r = 0, el = 0, ail = 24.1, rdr = 0, xcg = 0.25), expected = (cx = -0.004, cy = 0.025305, cz = -0.416, cl = -0.06266, cm = -0.0466, cn = -0.011799842), tol = 1e-06),
    (name = "Negative aileron", inputs = (vt = 300, alpha = 5, beta = 0, p = 0, q = 0, r = 0, el = 0, ail = -24.1, rdr = 0, xcg = 0.25), expected = (cx = -0.004, cy = -0.025305, cz = -0.416, cl = 0.06266, cm = -0.0466, cn = 0.011799842), tol = 1e-06),
    (name = "Positive rudder", inputs = (vt = 300, alpha = 5, beta = 0, p = 0, q = 0, r = 0, el = 0, ail = 0, rdr = 12.03, xcg = 0.25), expected = (cx = -0.004, cy = 0.034486, cz = -0.416, cl = 0.005614, cm = -0.0466, cn = -0.01934627173333), tol = 1e-06),
    (name = "Negative rudder", inputs = (vt = 300, alpha = 5, beta = 0, p = 0, q = 0, r = 0, el = 0, ail = 0, rdr = -12.03, xcg = 0.25), expected = (cx = -0.004, cy = -0.034486, cz = -0.416, cl = -0.005614, cm = -0.0466, cn = 0.01934627173333), tol = 1e-06),
    (name = "Aft CG", inputs = (vt = 300, alpha = 5, beta = 0, p = 0, q = 0, r = 0, el = 0, ail = 0, rdr = 0, xcg = 0.35), expected = (cx = -0.004, cy = 0, cz = -0.416, cl = 0, cm = -0.005, cn = 0), tol = 1e-06),
    (name = "Skewed inputs", inputs = (vt = 300, alpha = 16.2, beta = -3.24, p = 0.56, q = -0.76, r = -0.94, el = 4.567, ail = 7.654, rdr = -2.991, xcg = 0.123), expected = (cx = 0.04794994533333, cy = 0.02735386, cz = -0.72934852554344, cl = -0.026917840128, cm = -0.10638585796503, cn = 0.01118365476765), tol = 1e-06),
]
