#!/usr/bin/env python3
"""Generate the F-16 aero data module and checkcase fixtures from DAVE-ML.

Reads assets/F16_aero.dml (DAVE-ML encoding of the Stevens & Lewis F-16
aerodynamic tables, authored by Bruce Jackson, NASA LaRC; data lineage
NASA TP-1538 -> Stevens & Lewis -> NASA TM-2003-212145) and writes:

  src/f16_aero_data.jl        breakpoint vectors + 18 coefficient tables
  test/f16_aero_checkcases.jl 17 verification cases (inputs, expected outputs, tol)

Both outputs are marked autogenerated; rerun this script instead of editing them.
Only Python stdlib is used.

Data-lineage note (audited 2026-07-15): the DML encodes Morelli's 1995 Matlab
adaptation of the Stevens & Lewis 1992 first edition, and its embedded
checkcases were generated from Morelli's script. The S&L book listing in
assets/SnLtext.pdf (Appendix A, FUNCTION CL) differs from the DML in exactly
18 cells of the rolling-moment table Cl0(|beta|, alpha), all at alpha = 15,
20, 25 deg with |beta| >= 5 deg; every other table matches the book exactly.
Per the Step 0 scope (S&L book is the single authority), CL0_ABS below carries
the book values via BOOK_CL0_OVERRIDES, and the Morelli/DML original is kept
as CL0_ABS_DML so the NASA checkcases remain exactly reproducible.

Usage: python3 scripts/parse_f16_dml.py   (from the repo root)
"""

import xml.etree.ElementTree as ET
from pathlib import Path

NS = "{http://daveml.org/2010/DAVEML}"

DML_PATH = Path("assets/F16_aero.dml")
DATA_OUT = Path("src/f16_aero_data.jl")
CHECK_OUT = Path("test/f16_aero_checkcases.jl")

# DML breakpoint IDs -> Julia constant names
BP_NAMES = {
    "ALPHA1": "ALPHA_BP",      # deg, -10..45, 12 pts
    "BETA1": "BETA_ABS_BP",    # deg, 0..30, 7 pts (|beta| tables Cl0/Cn0)
    "BETA2": "BETA_BP",        # deg, -30..30, 7 pts (control-power tables)
    "DE1": "EL_BP",            # deg, -24..24, 5 pts
}

# DML function name -> Julia constant name for its table
TABLE_NAMES = {
    "Basic CX": "CX",
    "Basic CZ": "CZ",
    "Basic Cm": "CM",
    "Basic Cl": "CL0_ABS",
    "Basic Cn": "CN0_ABS",
    "CXq": "CXQ",
    "CYr": "CYR",
    "CYp": "CYP",
    "CZq": "CZQ",
    "Clr": "CLR",
    "Clp": "CLP",
    "Cmq": "CMQ",
    "Cnr": "CNR",
    "Cnp": "CNP",
    "dlda": "DLDA",
    "dldr": "DLDR",
    "dnda": "DNDA",
    "dndr": "DNDR",
}

# checkcase signal names -> short field names
SIGNAL_KEYS = {
    "trueAirspeed": "vt",
    "angleOfAttack": "alpha",
    "angleOfSideslip": "beta",
    "bodyAngularRate_Roll": "p",
    "bodyAngularRate_Pitch": "q",
    "bodyAngularRate_Yaw": "r",
    "elevatorDeflection": "el",
    "aileronDeflection": "ail",
    "rudderDeflection": "rdr",
    "bodyPositionOfCgWrtWingLeadingEdge_X": "xcg",
    "aeroBodyForceCoefficient_X": "cx",
    "aeroBodyForceCoefficient_Y": "cy",
    "aeroBodyForceCoefficient_Z": "cz",
    "aeroBodyMomentCoefficient_Roll": "cl",
    "aeroBodyMomentCoefficient_Pitch": "cm",
    "aeroBodyMomentCoefficient_Yaw": "cn",
}


# S&L book values for the Cl0(|beta|, alpha) cells where the book listing
# (assets/SnLtext.pdf, Appendix A, FUNCTION CL DATA block) diverges from the
# DML/Morelli encoding. Keys are (|beta| deg, alpha deg) -> book value.
BOOK_CL0_OVERRIDES = {
    (5, 15): -0.019, (5, 20): -0.020, (5, 25): -0.020,
    (10, 15): -0.034, (10, 20): -0.040, (10, 25): -0.037,
    (15, 15): -0.044, (15, 20): -0.050, (15, 25): -0.049,
    (20, 15): -0.046, (20, 20): -0.059, (20, 25): -0.061,
    (25, 15): -0.046, (25, 20): -0.068, (25, 25): -0.071,
    (30, 15): -0.047, (30, 20): -0.074, (30, 25): -0.079,
}


def parse_numbers(text):
    return [float(t) for t in text.replace(",", " ").split()]


def fmt(x):
    """Format a float preserving exact source values compactly."""
    s = repr(x)
    return s[:-2] if s.endswith(".0") else s


def julia_vector(vals):
    return "[" + ", ".join(fmt(v) for v in vals) + "]"


def julia_matrix(vals, nrows, ncols):
    """Row-major values -> Julia matrix literal, one source row per line."""
    rows = []
    for i in range(nrows):
        row = vals[i * ncols : (i + 1) * ncols]
        rows.append("    " + " ".join(fmt(v) for v in row))
    return "[\n" + ";\n".join(rows) + "\n]"


def main():
    root = ET.parse(DML_PATH).getroot()

    breakpoints = {}
    for bp in root.iter(f"{NS}breakpointDef"):
        breakpoints[bp.get("bpID")] = parse_numbers(bp.findtext(f"{NS}bpVals"))

    tables = []  # (julia_name, dml_name, bp_ids, values, description)
    for fn in root.iter(f"{NS}function"):
        name = fn.get("name")
        jname = TABLE_NAMES[name]
        bp_ids = [b.get("bpID") for b in fn.iter(f"{NS}bpRef")]
        vals = parse_numbers(fn.find(f".//{NS}dataTable").text)
        desc = " ".join((fn.findtext(f"{NS}description") or "").split())
        expected = 1
        for b in bp_ids:
            expected *= len(breakpoints[b])
        assert len(vals) == expected, f"{name}: {len(vals)} values, expected {expected}"
        tables.append((jname, name, bp_ids, vals, desc))

    shots = []
    for shot in root.iter(f"{NS}staticShot"):
        case = {"name": shot.get("name")}
        inputs, outputs, tols = {}, {}, []
        for sig in shot.find(f"{NS}checkInputs").iter(f"{NS}signal"):
            key = SIGNAL_KEYS[sig.findtext(f"{NS}signalName").strip()]
            inputs[key] = float(sig.findtext(f"{NS}signalValue"))
        for sig in shot.find(f"{NS}checkOutputs").iter(f"{NS}signal"):
            key = SIGNAL_KEYS[sig.findtext(f"{NS}signalName").strip()]
            outputs[key] = float(sig.findtext(f"{NS}signalValue"))
            tols.append(float(sig.findtext(f"{NS}tol")))
        case["inputs"], case["outputs"], case["tol"] = inputs, outputs, max(tols)
        shots.append(case)

    header = """\
# AUTOGENERATED by scripts/parse_f16_dml.py from assets/F16_aero.dml — do not edit.
#
# Stevens & Lewis F-16 aerodynamic data package.
# Source encoding: DAVE-ML example "F16_aero.dml" (Bruce Jackson, NASA Langley,
# 2002), https://daveml.org/examples/F16_aero.dml
# Data lineage: NASA TP-1538 (Nguyen et al., 1979) -> Stevens & Lewis,
# "Aircraft Control and Simulation" -> NASA TM-2003-212145 (Garza & Morelli).
#
# Units: all breakpoints in degrees; table values nondimensional.
# Interpolation contract (per the DML independentVarRef spec): linear, with
# inputs CLAMPED to the breakpoint range (extrapolate="neither").
# 2-D tables are stored (first breakpoint = rows, second = columns), matching
# the DML row-major layout where the last breakpoint dimension varies fastest.
"""

    lines = [header]
    lines.append('"Stevens & Lewis F-16 aerodynamic tables (see file header for provenance)."')
    lines.append("module F16AeroData\n")
    lines.append("# Reference geometry (English units, per the DML constants)")
    lines.append("const CBAR_FT = 11.32   # mean aerodynamic chord")
    lines.append("const BSPAN_FT = 30.0   # wing span")
    lines.append("const XCGR = 0.35       # reference CG, fraction of cbar\n")
    lines.append("# Breakpoints (deg)")
    for bp_id, jname in BP_NAMES.items():
        lines.append(f"const {jname} = {julia_vector(breakpoints[bp_id])}")
    lines.append("")
    for jname, dml_name, bp_ids, vals, desc in tables:
        dims = " x ".join(BP_NAMES[b] for b in bp_ids)
        lines.append(f'# "{dml_name}": {desc}')
        lines.append(f"# dims: {dims}")
        if jname == "CL0_ABS":
            beta_bp = breakpoints["BETA1"]
            alpha_bp = breakpoints["ALPHA1"]
            ncols = len(alpha_bp)
            book_vals = list(vals)
            for (b, a), v in BOOK_CL0_OVERRIDES.items():
                book_vals[beta_bp.index(b) * ncols + alpha_bp.index(a)] = v
            lines.append("# S&L book values (see the parser's data-lineage note); the")
            lines.append("# Morelli/DML original follows as CL0_ABS_DML.")
            lines.append(f"const {jname} = {julia_matrix(book_vals, len(beta_bp), ncols)}")
            lines.append("")
            lines.append("# As encoded in the DML (Morelli adaptation); referenced by the")
            lines.append("# NASA checkcase tests.")
            lines.append(f"const CL0_ABS_DML = {julia_matrix(vals, len(beta_bp), ncols)}")
        elif len(bp_ids) == 1:
            lines.append(f"const {jname} = {julia_vector(vals)}")
        else:
            nrows = len(breakpoints[bp_ids[0]])
            ncols = len(breakpoints[bp_ids[1]])
            lines.append(f"const {jname} = {julia_matrix(vals, nrows, ncols)}")
        lines.append("")
    lines.append("end # module F16AeroData")
    DATA_OUT.write_text("\n".join(lines) + "\n")

    clines = [
        "# AUTOGENERATED by scripts/parse_f16_dml.py from assets/F16_aero.dml — do not edit.",
        "# Verification checkcases embedded in the DAVE-ML source (staticShot elements).",
        "# Inputs: vt (ft/s), alpha/beta/el/ail/rdr (deg), p/q/r (rad/s), xcg (fraction of cbar).",
        "# Outputs: nondimensional body-axis coefficients. tol is the DML per-signal tolerance.",
        "",
        "const F16_AERO_CHECKCASES = [",
    ]
    for case in shots:
        ins = ", ".join(f"{k} = {fmt(v)}" for k, v in case["inputs"].items())
        outs = ", ".join(f"{k} = {fmt(v)}" for k, v in case["outputs"].items())
        clines.append(
            f'    (name = "{case["name"]}", inputs = ({ins}), '
            f"expected = ({outs}), tol = {fmt(case['tol'])}),"
        )
    clines.append("]")
    CHECK_OUT.write_text("\n".join(clines) + "\n")

    print(f"wrote {DATA_OUT}: {len(tables)} tables, {len(breakpoints)} breakpoint sets")
    print(f"wrote {CHECK_OUT}: {len(shots)} checkcases")


if __name__ == "__main__":
    main()
