using  DyadInterface, F16ModelWorkshop, DyadControlSystems, TOML

solution = F16LQGControllerAnalysis()

rows(M) = [collect(Float64.(r)) for r in eachrow(M)]
Cfb = solution.Cfb

open("assets/controller.toml", "w") do f
    println(f, "# Continuous LQG controller state space — auto-generated by")
    println(f, "# scripts/run_lqg_analysis.jl. Applied to the embedded block:")
    println(f, "#   BlockComponents.Continuous.StateSpace(..., apply \"dyad://F16ModelWorkshop/controller.toml\")")
    println(f, "# Matrices are nested arrays, row-major (outer array = first axis).")
    TOML.print(f, Dict("A" => rows(Cfb.A), "B" => rows(Cfb.B),
                       "C" => rows(Cfb.C), "D" => rows(Cfb.D)); sorted = true)
end


include("animate_trajectories_turbo.jl")
result2 = Scenario1ClosedLoop()

"""
STATE Symbols - :npos, :epos, :alt, :phi, :theta, :psi, :vt, :alpha, :beta, :P, :Q, :R
CONTROL Symbols = :T, :el, :ail, :rud, :lef

Generates an animation of the F16 trajectory with the specified state and control variables plotted over time. 
For visual clarity limited to three variables supplied as kwargs.
"""
fig = animate_trajectories_turbo(result2, duration=10.0;
                            plot1=:alt, 
                            plot2=:theta, 
                            plot3=:vt,
                            filename="closed_loop.mp4")