# Trim export, paired with the `partial analysis` in dyad/trim_export_analysis.dyad.
#
# A trim model declares its unknown controls and attitude `missing` (see
# `Tutorial.TrimDemo`). A zero-duration transient solve resolves them to the
# equilibrium, and the converged operating point is written as the three parameter-set
# assets that every later model applies:
#
#   trim_point.toml      F16PlantModel initial conditions
#   trim_reference.toml  `k`: state set-points [npos,epos,alt,phi,theta,psi,vt,alpha,beta,P,Q,R]
#   trim_controls.toml   `k`: control offsets [T,el,ail,rud,lef]
#
# The model must expose the plant as `f16plant` and the five commands as
# `T_cmd`, `el_cmd`, `ail_cmd`, `rud_cmd`, `lef_cmd` Constant blocks, as TrimDemo does.

using DyadInterface: AnalysisSolutionMetadata, ArtifactMetadata, ArtifactType,
                     artifacts, customizable_visualization, symbolic_container

const _TRIM_CONTROLS = ("T", "el", "ail", "rud", "lef")
# (plant state) => (F16PlantModel initial-condition parameter it seeds)
const _TRIM_STATES = (
    ("npos", "npos_init"), ("epos", "epos_init"), ("alt", "alt_init"),
    ("phi", "phi_init"), ("theta", "theta_init"), ("psi", "psi_init"),
    ("vt", "vt_init"), ("alpha", "alpha_init"), ("beta", "beta_init"),
    ("P", "P_init"), ("Q", "Q_init"), ("R", "R_init"),
)
const _TRIM_FILES = (
    "trim_point" => [
        "# F16 trim operating point, applied to an F16PlantModel instance:",
        "#   F16PlantModel(apply \"dyad://F16ModelWorkshop/trim_point.toml\")",
        "# A named argument after the clause overrides it (last-wins), which is how a",
        "# scenario perturbs one state off trim.",
    ],
    "trim_reference" => [
        "# State set-points [npos,epos,alt,phi,theta,psi,vt,alpha,beta,P,Q,R],",
        "# applied to the 12-channel reference VectorConstant.",
    ],
    "trim_controls" => [
        "# Trim control offsets [T,el,ail,rud,lef], applied to the 5-channel",
        "# trim VectorConstant.",
    ],
)

abstract type AbstractTrimExportAnalysisSpec <: AbstractAnalysisSpec end

"""
    TrimExportAnalysisSpec(; model, export_dir = "assets", abstol, reltol)

Trim `model` and write the operating point as `trim_point.toml`, `trim_reference.toml`
and `trim_controls.toml` under `export_dir` (a relative path resolves against the
package root). The default is the package's own `assets/`, the operating point the rest
of the workshop applies; pass another directory to trim a different flight condition
without replacing it.
"""
@kwdef mutable struct TrimExportAnalysisSpec <: AbstractTrimExportAnalysisSpec
    name::Symbol = :TrimExportAnalysis
    model::Union{Nothing, System} = nothing
    export_dir::String = "assets"
    abstol::Float64 = 1e-6
    reltol::Float64 = 1e-6
    overrides::_Overrides = _Overrides()
end

"""
    TrimExportAnalysisSolution

The zero-duration transient solution plus the exported operating point: `paramset`
holds one table per written file (`"trim_point"`, `"trim_reference"`,
`"trim_controls"`) and `files` the paths written.
"""
struct TrimExportAnalysisSolution{S} <: AbstractAnalysisSolution
    spec::TrimExportAnalysisSpec
    inner::S
    paramset::Dict{String, Dict{String, Any}}
    files::Vector{String}
end

Base.nameof(sol::TrimExportAnalysisSolution) = sol.spec.name

function DyadInterface.run_analysis(spec::TrimExportAnalysisSpec)
    inner = DyadInterface.run_analysis(TransientAnalysisSpec(;
        name = spec.name, model = spec.model, stop = 0.0,
        abstol = spec.abstol, reltol = spec.reltol, overrides = spec.overrides))
    sol = inner.sol
    m = symbolic_container(inner)
    at_trim(x) = Float64(sol(0.0, idxs = x))

    plant_init = Dict{String, Any}(
        init => at_trim(getproperty(m.f16plant, Symbol(state))) for (state, init) in _TRIM_STATES)
    paramset = Dict{String, Dict{String, Any}}(
        "trim_point" => plant_init,
        "trim_reference" => Dict{String, Any}("k" => [plant_init[init] for (_, init) in _TRIM_STATES]),
        "trim_controls" => Dict{String, Any}(
            "k" => [at_trim(getproperty(m, Symbol(c, "_cmd")).k) for c in _TRIM_CONTROLS]),
    )

    dir = _resolve_export(spec.export_dir)
    mkpath(dir)
    files = String[]
    for (name, header) in _TRIM_FILES
        path = joinpath(dir, name * ".toml")
        open(path, "w") do io
            println(io, "# Auto-generated by TrimExportAnalysis (retcode = ", sol.retcode,
                        "). Do not edit — rerun the trim.")
            foreach(line -> println(io, line), header)
            TOML.print(io, paramset[name]; sorted = true)
        end
        push!(files, path)
    end
    return TrimExportAnalysisSolution(spec, inner, paramset, files)
end

# The Studio-facing interface delegates to the inner transient solution and adds the
# exported operating point: `:TrimPoint` as a nested Dict and one download per file.
_file_artifact(path) = Symbol(first(splitext(basename(path))))

DyadInterface.symbolic_container(sol::TrimExportAnalysisSolution) = symbolic_container(sol.inner)

function DyadInterface.AnalysisSolutionMetadata(sol::TrimExportAnalysisSolution)
    inner_md = AnalysisSolutionMetadata(sol.inner)
    arts = ArtifactMetadata[
        ArtifactMetadata(:TrimPoint, ArtifactType.Native, "Trim point",
            "Trimmed operating point, one table per exported asset file."),
    ]
    for path in sol.files
        push!(arts, ArtifactMetadata(_file_artifact(path), ArtifactType.Download,
            basename(path), "Parameter set written to $path."))
    end
    append!(arts, inner_md.artifacts)
    return AnalysisSolutionMetadata(arts, inner_md.symbol_groups)
end

function DyadInterface.artifacts(sol::TrimExportAnalysisSolution, name::Symbol)
    name === :TrimPoint && return sol.paramset
    i = findfirst(path -> _file_artifact(path) === name, sol.files)
    i === nothing || return sol.files[i]
    return artifacts(sol.inner, name)
end

DyadInterface.customizable_visualization(sol::TrimExportAnalysisSolution, vizspec) =
    customizable_visualization(sol.inner, vizspec)

export AbstractTrimExportAnalysisSpec, TrimExportAnalysisSpec, TrimExportAnalysisSolution
