# Extendable tutorial export analyses.
#
# Each is a custom analysis paired with a `partial analysis` in
# dyad/Tutorial/export_analyses.dyad, so the tutorial .dyad files can `extends`
# them — the same pattern DyadControlSystems uses for LQGAnalysis / LinearAnalysis.
# A custom analysis's `run_analysis` may write a file (a plain Dyad analysis block
# cannot); these reuse the existing TrimPlantAnalysis / DyadControlSystems.LinearAnalysis
# machinery. Defined BEFORE the generated code, which references the `*Spec` types.

import DyadInterface
import DyadControlSystems
import Symbolics
import TOML
using DyadInterface: AbstractAnalysisSpec

const _SymPair = Dict{Symbolics.SymbolicT, Symbolics.SymbolicT}

# Relative export paths resolve against the package root (stable regardless of the
# working directory a component/analysis is built from).
_resolve_export(path::AbstractString) =
    isabspath(path) ? path : joinpath(_project_root(), path)

# ---- Trim export -----------------------------------------------------------
abstract type AbstractTrimExportAnalysisSpec <: AbstractAnalysisSpec end

@kwdef mutable struct TrimExportAnalysisSpec <: AbstractTrimExportAnalysisSpec
    name::Symbol = :TrimExportAnalysis
    model::Union{Nothing, System} = nothing
    export_path::String = "trim/tutorial_trim_point.toml"
    overrides::_SymPair = _SymPair()
end

# Delegates to TrimPlantAnalysis (defined after the generated code); the forward
# reference is fine because the method body is resolved at call time.
DyadInterface.run_analysis(spec::TrimExportAnalysisSpec) =
    DyadInterface.run_analysis(TrimPlantAnalysisSpec(; model = spec.model,
                                         export_path = _resolve_export(spec.export_path)))

export AbstractTrimExportAnalysisSpec, TrimExportAnalysisSpec

# ---- Linearization export --------------------------------------------------
abstract type AbstractLinearizeExportAnalysisSpec <: AbstractAnalysisSpec end

@kwdef mutable struct LinearizeExportAnalysisSpec <: AbstractLinearizeExportAnalysisSpec
    name::Symbol = :LinearizeExportAnalysis
    model::Union{Nothing, System} = nothing
    inputs::Vector{String} = String[]
    outputs::Vector{String} = String[]
    loop_openings::Vector{String} = String[]
    export_path::String = "trim/tutorial_linear_model.toml"
    overrides::_SymPair = _SymPair()
end

function DyadInterface.run_analysis(spec::LinearizeExportAnalysisSpec)
    lin = DyadControlSystems.LinearAnalysisSpec(; name = :LinearAnalysis,
        model = spec.model, inputs = spec.inputs, outputs = spec.outputs,
        loop_openings = spec.loop_openings)
    res = DyadInterface.run_analysis(lin)
    sys = res.sys
    rows(M) = [collect(Float64.(r)) for r in eachrow(Matrix(M))]
    paramset = Dict{String, Any}(
        "nx" => size(sys.A, 1), "nu" => size(sys.B, 2), "ny" => size(sys.C, 1),
        "inputs" => collect(String.(spec.inputs)),
        "outputs" => collect(String.(spec.outputs)),
        "A" => rows(sys.A), "B" => rows(sys.B), "C" => rows(sys.C), "D" => rows(sys.D),
    )
    path = _resolve_export(spec.export_path)
    mkpath(dirname(path))
    open(path, "w") do io
        println(io, "# Linearized F16 plant about trim — auto-generated by LinearizeExportAnalysis.")
        println(io, "# Open-loop plant P: control inputs (nu) -> measured outputs (ny).")
        TOML.print(io, paramset; sorted = true)
    end
    @info "Linearized plant written to $path"
    return res
end

export AbstractLinearizeExportAnalysisSpec, LinearizeExportAnalysisSpec
