using  DyadInterface, F16ModelWorkshop, F16ModelWorkshop.Tutorial, TOML

solution = TutorialLQG()

rows(M) = [collect(Float64.(r)) for r in eachrow(M)]
Cfb = solution.Cfb

open("assets/controller.toml", "w") do f
    println(f, "# Continuous LQG controller state space — auto-generated by")
    println(f, "# scripts/Tutorial/run_lqg_continuous_export.jl. Applied to the embedded block:")
    println(f, "#   BlockComponents.Continuous.StateSpace(..., apply \"dyad://F16ModelWorkshop/controller.toml\")")
    println(f, "# Matrices are nested arrays, row-major (outer array = first axis).")
    TOML.print(f, Dict("A" => rows(Cfb.A), "B" => rows(Cfb.B),
                       "C" => rows(Cfb.C), "D" => rows(Cfb.D)); sorted = true)
end
