using  DyadInterface, F16ModelWorkshop, F16ModelWorkshop.Tutorial, TOML

solution = TutorialDiscreteLQG()

rows(M) = [collect(Float64.(r)) for r in eachrow(M)]
Cfb = solution.Cfb
# Trim control offsets, folded into the controller output so controller.y is the
# absolute command.
y0 = TOML.parsefile("assets/trim_controls.toml")["k"]

open("assets/discrete_controller.toml", "w") do f
    println(f, "# Discrete (ZOH, Ts = ControllerTs) LQG controller — auto-generated by")
    println(f, "# scripts/Tutorial/run_lqg_discrete_export.jl. Applied to the clocked block:")
    println(f, "#   DiscreteComponents.DiscreteStateSpace(..., apply \"dyad://F16ModelWorkshop/discrete_controller.toml\")")
    println(f, "# Matrices are nested arrays, row-major (outer array = first axis).")
    TOML.print(f, Dict("A" => rows(Cfb.A), "B" => rows(Cfb.B),
                       "C" => rows(Cfb.C), "D" => rows(Cfb.D),
                       "y0" => collect(Float64.(y0))); sorted = true)
end
